
version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: sathishgajendran/dockerhelloworld:1.0
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50
      restart_policy: 
        condition: on-failure         
    ports:                                                                    - "8080:8080"      
    networks:                                                       
      - webnet                  
networks:     
  webnet:
